#ifndef _test
#define _test


/* AUTOGENERATED FILE --- IT IS UNWISE TO MODIFY*/
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <unistd.h>


//Function that will decode the above strings
char * decode_print_cat_7kgtf();

#endif /* _test.h */
